repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
      - id: ruff # Run the linter
        args: [--fix, --exit-non-zero-on-fix] # Optional: fix and exit on errors
      - id: ruff-format # Run the formatter
